version: '3'

server:
  command: "php roadrunner-worker.php"

http:
  address: "0.0.0.0:8080"
  workers:
    command: "php roadrunner-worker.php"
    pool:
      num_workers: 4
      max_jobs: 1000
  middleware:
    - gzip
    - headers

logs:
  mode: development
  level: error

gzip:
  compression_level: 5
